package dein.koldo.tablesmariadb.dao;

import dein.koldo.tablesmariadb.database.DataBaseConnection;
import dein.koldo.tablesmariadb.model.PersonaModel;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.time.LocalDate;

import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object responsible for managing {@link PersonaModel}
 * objects in the MariaDB database.
 *
 * <p>This class contains the SQL operations required to retrieve,
 * create, delete and restore people.</p>
 *
 * <p>Deletion is implemented using logical deletion. Rows are not
 * physically removed from the database. Instead, the {@code deleted}
 * column is modified.</p>
 *
 * @author Koldo
 */
public class PersonaDao {

    /**
     * Retrieves every non-deleted person from the database.
     *
     * @return list containing all active people
     * @throws SQLException if the database operation fails
     */
    public List<PersonaModel> findAll() throws SQLException {

        String sql = "SELECT id, first_name, last_name, birth_date FROM persona WHERE deleted = FALSE ORDER BY id";

        List<PersonaModel> personas = new ArrayList<>();

        try (
                Connection connection =
                        DataBaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(sql);

                ResultSet resultSet =
                        statement.executeQuery()
        ) {

            while (resultSet.next()) {

                PersonaModel persona = new PersonaModel(
                        resultSet.getInt("id"),
                        resultSet.getString("first_name"),
                        resultSet.getString("last_name"),
                        resultSet.getDate("birth_date").toLocalDate()
                );

                personas.add(persona);
            }
        }

        return personas;
    }

    /**
     * Inserts a new person into the database.
     *
     * <p>The identifier is automatically generated by MariaDB and
     * returned as part of the resulting {@link PersonaModel}.</p>
     *
     * @param firstName first name of the person
     * @param lastName last name of the person
     * @param birthDate birth date of the person
     *
     * @return the created person including its generated identifier
     *
     * @throws SQLException if the insertion fails or MariaDB does not
     *                      return the generated identifier
     */
    public PersonaModel insert(
            String firstName,
            String lastName,
            LocalDate birthDate
    ) throws SQLException {

        String sql = "INSERT INTO persona (first_name, last_name, birth_date) VALUES (?, ?, ?)";

        try (
                Connection connection =
                        DataBaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(
                                sql,
                                Statement.RETURN_GENERATED_KEYS
                        )
        ) {

            statement.setString(1, firstName);
            statement.setString(2, lastName);
            statement.setDate(
                    3,
                    Date.valueOf(birthDate)
            );

            statement.executeUpdate();

            try (ResultSet generatedKeys =
                         statement.getGeneratedKeys()) {

                if (generatedKeys.next()) {

                    return new PersonaModel(
                            generatedKeys.getInt(1),
                            firstName,
                            lastName,
                            birthDate
                    );
                }
            }
        }

        throw new SQLException(
                "No se ha podido obtener el ID generado."
        );
    }

    /**
     * Marks the specified people as deleted.
     *
     * <p>The operation is performed inside a transaction so either
     * every selected person is deleted or none of them are.</p>
     *
     * @param personas people that should be deleted
     * @throws SQLException if the database operation fails
     */
    public void delete(List<PersonaModel> personas)
            throws SQLException {

        String sql = "UPDATE persona SET deleted = TRUE WHERE id = ? \n";

        try (
                Connection connection =
                        DataBaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(sql)
        ) {

            connection.setAutoCommit(false);

            try {

                for (PersonaModel persona : personas) {

                    statement.setInt(
                            1,
                            persona.getId()
                    );

                    statement.addBatch();
                }

                statement.executeBatch();

                connection.commit();

            } catch (SQLException exception) {

                connection.rollback();

                throw exception;

            } finally {

                connection.setAutoCommit(true);
            }
        }
    }

    /**
     * Restores every person that was previously logically deleted.
     *
     * @throws SQLException if the database operation fails
     */
    public void restoreAll() throws SQLException {

        String sql = " UPDATE persona SET deleted = FALSE WHERE deleted = TRUE";

        try (
                Connection connection =
                        DataBaseConnection.getConnection();

                PreparedStatement statement =
                        connection.prepareStatement(sql)
        ) {

            statement.executeUpdate();
        }
    }
}